import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _data = {
    'en': {
      'app_name': 'E-Library',
      'settings': 'Settings',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'toggle_theme': 'Toggle dark/light theme',
      'font_size': 'Font Size',
      'adjust_font': 'Adjust text size',
      'small': 'Small',
      'medium': 'Medium',
      'large': 'Large',
      'extra_large': 'Extra Large',
      'language': 'Language',
      'choose_language': 'Choose your preferred language',
      'english': 'English',
      'khmer': 'ភាសាខ្មែរ',
      'general': 'General',
      'about': 'About',
      'version': 'Version 1.0.0',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'books_read': 'Books Read',
      'favorites': 'Favorites',
      'hours': 'Hours',
      'downloads': 'Downloads',
      'manage_offline': 'Manage offline books',
      'notifications': 'Notifications',
      'reading_reminders': 'Reading reminders and updates',
      'help_support': 'Help & Support',
      'faqs_contact': 'FAQs and contact us',
      'sign_out': 'Sign Out',
      'home': 'Home',
      'search': 'Search',
      'library': 'Library',

      'welcome_back': 'Welcome Back',
      'sign_in_continue': 'Sign in to continue',
      'email': 'Email',
      'enter_email': 'Please enter your email',
      'valid_email': 'Please enter a valid email',
      'password': 'Password',
      'enter_password': 'Please enter your password',
      'password_min': 'Password must be at least 6 characters',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'or_continue_with': 'or continue with',
      'no_account': 'Don\'t have an account?',
      'sign_up': 'Sign Up',
      'login_failed': 'Login failed',

      'discover_knowledge': 'Discover knowledge anytime, anywhere',
      'hello': 'Hello',
      'reader': 'Reader',
      'what_to_read': 'What do you want to read today?',
      'read_now': 'Read Now',
      'categories': 'Categories',
      'see_all': 'See All',
      'all': 'All',
      'recommended': 'Recommended',
      'list_view': 'List view',
      'grid_view': 'Grid view',
      'continue_reading': 'Continue Reading',
      'percent_complete': '% complete',
      'popular_books': 'Popular Books',

      'profile_section': 'PROFILE',
      'name': 'Name',
      'name_updated': 'Name updated',
      'name_updated_success': 'Name updated successfully',
      'failed_name': 'Failed to update name',
      'set_password': 'SET PASSWORD',
      'set_password_hint': 'You signed up via Google. Create a password for email login.',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'confirm_new_password': 'Confirm New Password',
      'passwords_no_match': 'Passwords do not match',
      'create_password': 'Create Password',
      'change_password': 'CHANGE PASSWORD',
      'change_password_btn': 'Change Password',
      'old_password': 'Old Password',
      'enter_old_password': 'Please enter your old password',
      'password_changed': 'Password changed successfully',
      'failed_password_change': 'Failed to change password',
      'password_created': 'Password created successfully',
      'failed_password_create': 'Failed to create password',
      'take_photo': 'Take Photo',
      'choose_gallery': 'Choose from Gallery',
      'photo_updated': 'Profile photo updated',
      'failed_photo': 'Failed to update photo',
      'tap_change_photo': 'Tap to change photo',
      'photo_updated_label': 'Photo updated',
      'save': 'Save',
      'enter_password_generic': 'Please enter a password',
      'password_8_chars': 'Must be at least 8 characters',
      'password_uppercase': 'Must contain an uppercase letter',
      'password_digit': 'Must contain a digit',
      'password_special': 'Must contain a special character',
      'please_confirm_password': 'Please confirm your password',
      'please_confirm_new_password': 'Please confirm your new password',

      'cancel': 'Cancel',
      'all_filter': 'All',
      'books_filter': 'Books',
      'pdfs_filter': 'PDFs',
      'no_results': 'No Results',
      'something_wrong': 'Something went wrong',
      'try_different': 'Try a different search term',
      'retry': 'Retry',
      'pdf_badge': 'PDF',
      'unexpected_search': 'Unexpected search response format',

      'recently_read': 'Recently Read',
      'failed_load_books': 'Failed to load books',
      'no_books_category': 'No books in this category',

      'user': 'User',
      'books': 'Books',
      'tags': 'Tags',
      'publish_year': 'Year',
    },
    'km': {
      'app_name': 'បណ្ណាល័យអេឡិចត្រូនិក',
      'settings': 'ការកំណត់',
      'appearance': 'រូបរាង',
      'dark_mode': 'របៀបងងឹត',
      'toggle_theme': 'ប្តូររបៀបងងឹត/ភ្លឺ',
      'font_size': 'ទំហំអក្សរ',
      'adjust_font': 'កែតម្រូវទំហំអក្សរ',
      'small': 'តូច',
      'medium': 'មធ្យម',
      'large': 'ធំ',
      'extra_large': 'ធំខ្លាំង',
      'language': 'ភាសា',
      'choose_language': 'ជ្រើសរើសភាសាដែលអ្នកចូលចិត្ត',
      'english': 'English',
      'khmer': 'ភាសាខ្មែរ',
      'general': 'ទូទៅ',
      'about': 'អំពី',
      'version': 'កំណែ 1.0.0',
      'profile': 'ប្រវត្តិរូប',
      'edit_profile': 'កែប្រវត្តិរូប',
      'books_read': 'សៀវភៅបានអាន',
      'favorites': 'ចំណូលចិត្ត',
      'hours': 'ម៉ោង',
      'downloads': 'ទាញយក',
      'manage_offline': 'គ្រប់គ្រងសៀវភៅក្រៅបណ្តាញ',
      'notifications': 'ការជូនដំណឹង',
      'reading_reminders': 'ការរំលឹកការអាន',
      'help_support': 'ជំនួយ',
      'faqs_contact': 'សំណួរញឹកញាប់ និងទំនាក់ទំនង',
      'sign_out': 'ចាកចេញ',
      'home': 'ទំព័រដើម',
      'search': 'ស្វែងរក',
      'library': 'បណ្ណាល័យ',

      'welcome_back': 'សូមស្វាគមន៍មកកាន់',
      'sign_in_continue': 'ចូលគណនីដើម្បីបន្ត',
      'email': 'អ៊ីមែល',
      'enter_email': 'សូមបញ្ចូលអ៊ីមែល',
      'valid_email': 'សូមបញ្ចូលអ៊ីមែលត្រឹមត្រូវ',
      'password': 'ពាក្យសម្ងាត់',
      'enter_password': 'សូមបញ្ចូលពាក្យសម្ងាត់',
      'password_min': 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ ៦ តួអក្សរ',
      'forgot_password': 'ភ្លេចពាក្យសម្ងាត់?',
      'sign_in': 'ចូលគណនី',
      'or_continue_with': 'ឬបន្តជាមួយ',
      'no_account': 'មិនទាន់មានគណនីទេ?',
      'sign_up': 'ចុះឈ្មោះ',
      'login_failed': 'ការចូលគណនីបរាជ័យ',

      'discover_knowledge': 'ស្វែងយល់ចំណេះដឹងគ្រប់ពេល គ្រប់ទីកន្លែង',
      'hello': 'សួស្តី',
      'reader': 'អ្នកអាន',
      'what_to_read': 'តើអ្នកចង់អានអ្វីថ្ងៃនេះ?',
      'read_now': 'អានឥឡូវនេះ',
      'categories': 'ប្រភេទ',
      'see_all': 'មើលទាំងអស់',
      'all': 'ទាំងអស់',
      'recommended': 'បានណែនាំ',
      'list_view': 'ទិដ្ឋភាពបញ្ជី',
      'grid_view': 'ទិដ្ឋភាពក្រឡា',
      'continue_reading': 'បន្តការអាន',
      'percent_complete': '% បានអាន',
      'popular_books': 'សៀវភៅពេញនិយម',

      'profile_section': 'ប្រវត្តិរូប',
      'name': 'ឈ្មោះ',
      'name_updated': 'ឈ្មោះត្រូវបានធ្វើបច្ចុប្បន្នភាព',
      'name_updated_success': 'ឈ្មោះត្រូវបានធ្វើបច្ចុប្បន្នភាពដោយជោគជ័យ',
      'failed_name': 'បរាជ័យក្នុងការធ្វើបច្ចុប្បន្នភាពឈ្មោះ',
      'set_password': 'កំណត់ពាក្យសម្ងាត់',
      'set_password_hint': 'អ្នកបានចុះឈ្មោះតាមរយៈ Google។ បង្កើតពាក្យសម្ងាត់សម្រាប់ចូលគណនីតាមអ៊ីមែល។',
      'new_password': 'ពាក្យសម្ងាត់ថ្មី',
      'confirm_password': 'បញ្ជាក់ពាក្យសម្ងាត់',
      'confirm_new_password': 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
      'passwords_no_match': 'ពាក្យសម្ងាត់មិនត្រូវគ្នា',
      'create_password': 'បង្កើតពាក្យសម្ងាត់',
      'change_password': 'ប្តូរពាក្យសម្ងាត់',
      'change_password_btn': 'ប្តូរពាក្យសម្ងាត់',
      'old_password': 'ពាក្យសម្ងាត់ចាស់',
      'enter_old_password': 'សូមបញ្ចូលពាក្យសម្ងាត់ចាស់',
      'password_changed': 'ពាក្យសម្ងាត់ត្រូវបានផ្លាស់ប្តូរដោយជោគជ័យ',
      'failed_password_change': 'បរាជ័យក្នុងការផ្លាស់ប្តូរពាក្យសម្ងាត់',
      'password_created': 'ពាក្យសម្ងាត់ត្រូវបានបង្កើតដោយជោគជ័យ',
      'failed_password_create': 'បរាជ័យក្នុងការបង្កើតពាក្យសម្ងាត់',
      'take_photo': 'ថតរូប',
      'choose_gallery': 'ជ្រើសរើសពីវិចិត្រសាល',
      'photo_updated': 'រូបថតប្រវត្តិរូបត្រូវបានធ្វើបច្ចុប្បន្នភាព',
      'failed_photo': 'បរាជ័យក្នុងការធ្វើបច្ចុប្បន្នភាពរូបថត',
      'tap_change_photo': 'ប៉ះដើម្បីប្តូររូបថត',
      'photo_updated_label': 'រូបថតត្រូវបានធ្វើបច្ចុប្បន្នភាព',
      'save': 'រក្សាទុក',
      'enter_password_generic': 'សូមបញ្ចូលពាក្យសម្ងាត់',
      'password_8_chars': 'ត្រូវមានយ៉ាងហោចណាស់ ៨ តួអក្សរ',
      'password_uppercase': 'ត្រូវមានអក្សរធំមួយតួ',
      'password_digit': 'ត្រូវមានលេខមួយតួ',
      'password_special': 'ត្រូវមានតួអក្សរពិសេសមួយតួ',
      'please_confirm_password': 'សូមបញ្ជាក់ពាក្យសម្ងាត់',
      'please_confirm_new_password': 'សូមបញ្ជាក់ពាក្យសម្ងាត់ថ្មី',

      'cancel': 'បោះបង់',
      'all_filter': 'ទាំងអស់',
      'books_filter': 'សៀវភៅ',
      'pdfs_filter': 'PDF',
      'no_results': 'គ្មានលទ្ធផល',
      'something_wrong': 'មានបញ្ហាកើតឡើង',
      'try_different': 'សាកល្បងពាក្យស្វែងរកផ្សេង',
      'retry': 'ព្យាយាមម្តងទៀត',
      'pdf_badge': 'PDF',
      'unexpected_search': 'ទម្រង់ចម្លើយស្វែងរកមិនត្រឹមត្រូវ',

      'recently_read': 'ទើបអានថ្មីៗ',
      'failed_load_books': 'បរាជ័យក្នុងការទាញយកសៀវភៅ',
      'no_books_category': 'គ្មានសៀវភៅក្នុងប្រភេទនេះទេ',

      'user': 'អ្នកប្រើប្រាស់',
      'books': 'សៀវភៅ',
      'tags': 'ស្លាក',
      'publish_year': 'ឆ្នាំ',
    },
  };

  String translate(String key) {
    return _data[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'km'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
